from domain import CreateTokenUsecase, GetWorkerByTokenUsecase, RegisterWorkerUsecase


create_token: CreateTokenUsecase
register_worker: RegisterWorkerUsecase
get_worker_by_token: GetWorkerByTokenUsecase
