"""add_jira_id

Revision ID: 8ff2d595b933
Revises: a04fb413bbaa
Create Date: 2024-03-16 23:57:33.117789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff2d595b933'
down_revision: Union[str, None] = 'a04fb413bbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('jira_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'jira_id')
    # ### end Alembic commands ###
