"""initial

Revision ID: ac5dadce511d
Revises: 
Create Date: 2024-03-03 18:41:42.995674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5dadce511d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTATOR', 'ACCOUNTANT', 'DEVELOPER', 'MANAGER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('OPENED', 'CLOSED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('workers')
    # ### end Alembic commands ###
